### ISSUE TITLE
Fix LICENSE

### ISSUE THREAD

**Issue by pocc** [purrleterian/Image-to-ASCII-art-converter#3]
I presume that your name is not `[name of copyright owner]`. Check line 188.

**Comment by purrleterian** [comment]
Oh, thanks. This is the first time I'm putting a project on Github, so I don't really know what I'm doing. Thanks for pointing that out.

**Comment by pocc** [comment]
Yeah I had projects up for months without realizing the LICENSE file needed to be altered.

**Comment by pocc** [comment]
[<img src="https://www.zeldadungeon.net/wp-content/uploads/2015/02/0c48413.jpg">](https://docs.python-guide.org/writing/structure/) 
-- courtesy of Kenneth Reitz
